# Generated by Django 5.0.2 on 2024-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="parent_message",
            field=models.IntegerField(null=True, verbose_name="回复的留言id"),
        ),
    ]
