# Generated by Django 5.0.2 on 2024-03-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="文章标题")),
                ("category", models.CharField(max_length=50, verbose_name="文章分类")),
                ("limit", models.CharField(max_length=20, verbose_name="权限")),
                ("introduce", models.CharField(max_length=90, verbose_name="文章简介")),
                ("content", models.TextField(verbose_name="文章内容")),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.userprofile",
                    ),
                ),
            ],
        ),
    ]
